AuctionPlatform/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('listings/', include('listings.urls')),
    path('', RedirectView.as_view(url='listings/', permanent=True))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', views.register, name="register"),
    path('profile/', views.profile, name="profile"),
    path('seller_profile/<str:username>', views.seller_profile, name="seller_profile")
]

listings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from . import views
from .views import *
app_name = 'listings'
urlpatterns = [
    path('', views.listings, name='home'),
    path('listing/<str:pk>', views.listing, name='listing'),
    path('api/records/', views.record_suggestion_list, name='record_suggestion_list'),
    path('add_listing/', views.add_listing, name='add_listing'),
    path('search/', views.search, name='search'),
    path('add_record/', views.add_record, name='add_record'),
    path('create_order/<str:pk>/<str:price>', views.create_order, name='create_order')
    ]

listings/models.py
import random
import string

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
def directory_path(instance, filename):
    return "db_files/{0}.png".format(generate_random_string(8))


def generate_random_string(length):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))


COUNTRIES = (
    ('afghanistan', 'Afghanistan'),
    ('albania', 'Albania'),
    ('algeria', 'Algeria'),
    ('argentina', 'Argentina'),
    ('australia', 'Australia'),
    ('austria', 'Austria'),
    ('bangladesh', 'Bangladesh'),
    ('brazil', 'Brazil'),
    ('canada', 'Canada'),
    ('china', 'China'),
    ('colombia', 'Colombia'),
    ('egypt', 'Egypt'),
    ('france', 'France'),
    ('germany', 'Germany'),
    ('india', 'India'),
    ('indonesia', 'Indonesia'),
    ('iran', 'Iran'),
    ('iraq', 'Iraq'),
    ('italy', 'Italy'),
    ('japan', 'Japan'),
    ('mexico', 'Mexico'),
    ('netherlands', 'Netherlands'),
    ('nigeria', 'Nigeria'),
    ('pakistan', 'Pakistan'),
    ('peru', 'Peru'),
    ('philippines', 'Philippines'),
    ('poland', 'Poland'),
    ('russia', 'Russia'),
    ('saudi arabia', 'Saudi Arabia'),
    ('south africa', 'South Africa'),
    ('south korea', 'South Korea'),
    ('spain', 'Spain'),
    ('sweden', 'Sweden'),
    ('switzerland', 'Switzerland'),
    ('thailand', 'Thailand'),
    ('turkey', 'Turkey'),
    ('ukraine', 'Ukraine'),
    ('united arab emirates', 'United Arab Emirates'),
    ('united kingdom', 'United Kingdom'),
    ('united states', 'United States'),
    ('venezuela', 'Venezuela'),
    ('vietnam', 'Vietnam'),
    ('yemen', 'Yemen'))


class Artist(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, choices=COUNTRIES)

    def __str__(self):
        return self.name


class Record(models.Model):
    GENRES = (
        ('pop', 'Pop'),
        ('rock', 'Rock'),
        ('hip hop', 'Hip Hop'),
        ('jazz', 'Jazz'),
        ('blues', 'Blues'),
        ('country', 'Country'),
        ('classical', 'Classical'),
        ('electronic', 'Electronic'),
        ('folk', 'Folk'),
        ('r&b', 'R&B'),
        ('reggae', 'Reggae'),
        ('punk', 'Punk'),
        ('metal', 'Metal'),
        ('indie', 'Indie'),
        ('rap', 'Rap'),
        ('soul', 'Soul'),
        ('funk', 'Funk'),
        ('dance', 'Dance'),
        ('ambient', 'Ambient'))
    title = models.CharField(max_length=100, blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    artist = models.ForeignKey(Artist, on_delete=models.SET_NULL, null=True)
    genre = models.CharField(max_length=100, blank=True, null=True, choices=GENRES)
    country = models.CharField(max_length=100, blank=True, null=True, choices=COUNTRIES)
    image = models.ImageField(upload_to=directory_path, null=True, blank=True)

    def __str__(self):
        return self.title


class Listing(models.Model):
    MEDIUM = (('CD', 'CD'),
              ('Vinyl', 'Vinyl'),
              ('Cassete', 'Casette'),
              ('Other', 'Other')
              )
    CONDITION = (('new', 'New'),
                 ('used', 'Used'))
    record = models.ForeignKey(Record, on_delete=models.SET_NULL, null=True)
    sellerID = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    buy_now = models.BooleanField(default=False)
    buy_now_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    bidding = models.BooleanField(default=True)
    bidding_starting_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    medium = models.CharField(max_length=10, choices=MEDIUM, default='CD')
    description = models.TextField(null=True, blank=True)
    condition = models.CharField(max_length=40, choices=CONDITION, default='New')
    date_added = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.id)


class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    ListingID = models.ForeignKey(Listing, on_delete=models.SET_NULL, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.ListingID) + " - " + str(self.ListingID.record.title) + " - " + str(self.price) + "PLN"


class Order(models.Model):
    STATUS = (('pending', 'Pending'),
              ('completed', 'Completed'),
              ('cancelled', 'Cancelled'),
              ('delivered', 'Delivered'),
              ('out for delivery', 'Out for delivery'),
              ('awaiting payment', 'Awaiting Payment')
              )
    buyer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    ListingID = models.ForeignKey(Listing, on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=20, choices=STATUS, default='pending')
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

listings/forms.py
from django import forms
from .models import Listing, Artist, Record, Bid




class AddListingForm(forms.ModelForm):
    title = forms.CharField(max_length=100, required=False)

    class Meta:
        model = Listing
        fields = [
            'title',
            'buy_now',
            'bidding',
            'buy_now_price',
            'bidding_starting_price',
            'medium',
            'description',
            'condition',
            'end_time',
        ]
        widgets = {
            'end_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }
class AddRecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = [
            'title',
            'artist',
            'country',
            'year',
            'genre',
            'image'
        ]
    def clean(self):
        cleaned_data = super().clean()
        print(cleaned_data)
        return cleaned_data

class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['price']
        labels = {'price': 'Your Bid:'}

listings/views.py
from django.contrib.auth.decorators import login_required
from django.core.serializers import serialize
from django.db.models import Max
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import ListingSerializer, ArtistSerializer, RecordSerializer
from .forms import AddListingForm, AddRecordForm, BidForm

from listings.models import Listing, Artist, Record, Order
from django.contrib.auth.models import User




@api_view(['GET'])
def record_suggestion_list(request):
    query = request.GET

    if query.get('title', ''):
        suggestions = Record.objects.filter(title__icontains=query.get('title', ''))[:10]
        serializer = RecordSerializer(suggestions, many=True)
    elif query.get('artist', ''):
        suggestions = Artist.objects.filter(name__icontains=query.get('artist', ''))[:10]
        serializer = ArtistSerializer(suggestions, many=True)
    elif query.get('country', ''):
        suggestions = Record.objects.filter(country__icontains=query.get('country', ''))[:10]
        serializer = RecordSerializer(suggestions, many=True)
    else:
        suggestions = Record.objects.all()[:10]
        serializer = RecordSerializer(suggestions, many=True)

    data = {'suggestions': serializer.data}

    if query.get('format') == 'xml':
        xml_data = serialize('xml', suggestions)
        response = HttpResponse(xml_data, content_type='text/xml')
        return response
    elif query.get('format') == 'json':
        return JsonResponse(data)

    return Response(data)
def listings(request):
    listings = Listing.objects.all()
    context = {'listings': listings}

    return render(request, 'listings/listings.html', context)
def listing(request, pk):
    listing = Listing.objects.get(pk=pk)
    max_bid = listing.bid_set.all().order_by('-price').first()

    starting_price = listing.bidding_starting_price


    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('/accounts/login')
        form = BidForm(request.POST)
        if form.is_valid():
            bid = form.save(commit=False)
            bid.bidder = request.user
            bid.ListingID = listing
            bid.save()
            max_bid = bid
    if listing.bidding and max_bid:
        form = BidForm(initial={'price': max_bid.price+1})
    elif listing.bidding:
        form = BidForm(initial={'price':starting_price+1})
    else:
        form = BidForm()
    context = {'listing': listing, 'form': form, 'max_bid': max_bid, 'starting_price': starting_price}

    return render(request, 'listings/listing.html', context)



@login_required
def add_listing(request):
    if request.method == 'POST':
        listing_form = AddListingForm(request.POST)


        if listing_form.is_valid():
            title = listing_form.cleaned_data['title']

            if Record.objects.filter(title__iexact=title).exists():
                tmp_form = listing_form.save(commit=False)
                tmp_form.record = Record.objects.get(title__iexact=title)
                tmp_form.sellerID = request.user
                tmp_form.save()

            else:
                buy_now = listing_form.cleaned_data.get('buy_now')
                buy_now_price = listing_form.cleaned_data.get('buy_now_price')
                bidding = listing_form.cleaned_data.get('bidding')
                bidding_starting_price = listing_form.cleaned_data.get('bidding_starting_price')
                medium = listing_form.cleaned_data.get('medium')
                description = listing_form.cleaned_data.get('description')
                condition = listing_form.cleaned_data.get('condition')
                end_time = listing_form.cleaned_data.get('end_time')

                request.session['title'] = title
                request.session['buy_now'] = buy_now
                request.session['buy_now_price'] = str(buy_now_price)
                request.session['bidding'] = bidding
                request.session['bidding_starting_price'] = str(bidding_starting_price)
                request.session['medium'] = medium
                request.session['description'] = description
                request.session['condition'] = condition
                request.session['end_time'] = str(end_time)

                return redirect('listings:add_record')
            username = request.user.username
            return redirect('/accounts/seller_profile/{username}'.format(username=username))

    if request.session.get('title') is None:
        listing_form = AddListingForm()
    else:
        initial_data = {
            'title': request.session.pop('title', None),
            'buy_now': request.session.pop('buy_now', None),
            'buy_now_price': request.session.pop('buy_now_price', None),
            'bidding': request.session.pop('bidding', None),
            'bidding_starting_price': request.session.pop('bidding_starting_price', None),
            'medium': request.session.pop('medium', None),
            'description': request.session.pop('description', None),
            'condition': request.session.pop('condition', None),
            'end_time': request.session.pop('end_time', None),
        }
        listing_form = AddListingForm(initial=initial_data)

    return render(request, 'listings/add_listing.html', {'listing_form': listing_form})

@login_required
def add_record(request):
    title = request.session.get('title', None)
    if request.method == 'POST':
        record_form = AddRecordForm(request.POST, request.FILES)
        if record_form.is_valid():
            record_form.save()
            return redirect('listings:add_listing')

    else:
        record_form = AddRecordForm(initial={'title': title})

    context = {'record_form': record_form}
    return render(request, 'listings/add_record.html', context)

def search(request):
    title = request.GET.get('title')
    artist = request.GET.get('artist')
    country = request.GET.get('country')
    record_format = request.GET.get('format')
    year = request.GET.get('year')

    # Construct a query based on the parameters
    query = {}
    if title:
        query['record__title__icontains'] = title
    if artist:
        query['record__artist__name__icontains'] = artist
    if country:
        query['record__country__icontains'] = country
    if record_format:
        query['medium'] = record_format
    if year:
        query['record__year'] = year

    filtered_listings = Listing.objects.filter(**query)
    context = {'listings': filtered_listings}

    return render(request, "listings/listings.html", context)

@login_required
def create_order(request, pk, price):
    listing = Listing.objects.get(pk=pk)
    if request.method == 'POST':
        order = Order.objects.create(ListingID=listing, buyer=request.user, price=price)
        listing.active = False
        listing.save()
    return redirect('/accounts/profile')

listings/templates/listings/add_listing.html
{% extends "listings/main.html" %}
{% load static %}
{% load compress %}

{% block header %}
    <title>Add listing</title>
    {% compress css %}
        <link rel='stylesheet' type="text/x-scss" href="{% static '/css/forms.scss' %}">
    {% endcompress %}
{% endblock %}

{% block content %}

    <div class="post-form-container">
    <h2>Add Listing:</h2>
        <form id="addListingForm" method="post" class="post-form">
            {% csrf_token %}

            {% for field in listing_form %}

                <div>
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}

                    {% if field.errors %}
                        <ul class="errorlist">
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    {% if field.help_text %}
                        <p class="helptext">{{ field.help_text }}</p>
                    {% endif %}
                </div>
            {% endfor %}

            <div>
                <button type="submit">Add Listing</button>
            </div>
        </form>
    </div>

{% endblock %}

listings/templates/listings/add_record.html
{% extends "listings/main.html" %}
{% load static %}
{% load compress %}
{% block header %}
    <title>Add Record</title>
    {% compress css %}
    <link rel='stylesheet' type="text/x-scss" href="{% static '/css/forms.scss' %}">
    {% endcompress %}

{% endblock %}

{% block content %}
    <div class="post-form-container">
        <h2>Add Record:</h2>


        <form id="addRecordForm" enctype="multipart/form-data" method="post" class="post-form">
            {% csrf_token %}

            {% for field in record_form %}

                <div>
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}

                </div>
            {% endfor %}
        <div>
                <button type="submit">Add Record</button>
            </div>

        </form>
    </div>

{% endblock %}

listings/templates/listings/listing.html
{% extends 'listings/main.html' %}
{% load static %}

{% block header %}
    <title>{{ listing.record.title }}</title>
    <link rel='stylesheet' type="text/css" href="{% static '/css/listing.css' %}">
{% endblock %}


{% block content %}


    <div class="listing-container-2">
        <div class=listing-image>{% if listing.record.image %}
            <div class="image-container"><img src="{{ listing.record.image.url }}" alt="imag"></div>
        {% else %}
            <p>No image available</p>
        {% endif %}</div>
        <div class="buy-info-container">
            <div class="listing-price">

                <a href="/accounts/seller_profile/{{ listing.sellerID.username }}"><h4>
                    Seller: {{ listing.sellerID.username }}</h4></a>
                {% if listing.buy_now %}
                    <form method="post" action="{% url 'listings:create_order' listing.id listing.buy_now_price %}">
                        {% csrf_token %}
                        <button type=submit>Buy now: {{ listing.buy_now_price }}</button>
                    </form>
                {% endif %}


                {% if listing.buy_now and listing.bidding %}
                    or
                {% endif %}

                {% if listing.bidding %}

                    <form method="post" action="{% url 'listings:listing' pk=listing.pk %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Place Bid</button>
                    </form>
                    {% if max_bid %}
                        Current highest bid: {{ max_bid.price }}
                    {% else %}
                        Starting price: {{ starting_price }}
                    {% endif %}
                    {% if max_bid.bidder == user %}
                        <h6>Your bid is currently the highest.<h6>
                    {% endif %}
                {% endif %}
            </div>
            <br>
            <div>Auction ends:
                <br>
                {{ listing.end_time }}</div>
        </div>

        <div><h1>{{ listing.record.title }}</h1></div>
        <div class="listing-artist"><h2>By {{ listing.record.artist }}</h2></div>
        <div class="listing-country-year">{{ listing.record.country|capfirst }}, {{ listing.record.year }}</div>
        <div class="listing-medium">Format: {{ listing.medium|capfirst }}</div>
        <div class="listing-genre">Genre: {{ listing.record.genre|capfirst }}</div>
        <div class="listing-condition">
            {% if listing.condition %}
                Condition: New
            {% else %}
                Condition: Used
            {% endif %}
        </div>


        <div class="listing-description">
            <br>
            <hr>
            <h4>Description:</h4>
            {{ listing.description }}</div>
    </div>
{% endblock %}

listings/templates/listings/listings.html
{% extends 'listings/main.html' %}
{% load static %}

{% block header %}
    <title>Listings</title>
    <link rel='stylesheet' type="text/css" href="{% static '/css/listings.css' %}">
    <script src="{% static '/js/autocomplete.js' %}" defer></script>
{% endblock %}
{% block content %}
{% include 'listings/listings_filtering.html' %}
{% endblock %}

listings/templates/listings/listings_filtering.html
<div class="listing-container">
        {% for i in listings %}
            {% if i.active %}
                <div class='listing'>
                    <a href="{% url 'listings:listing' i.id %}">
                        <div class="img-column">

                            {% if i.record.image %}
                                <div class="image-container">
                                    <img src="{{ i.record.image.url }}" alt="image">
                                </div>
                            {% else %}
                                <p>No image available</p>
                            {% endif %}
                        </div>
                    </a>


                    <div class="info-column">
                        <a href="{% url 'listings:listing' i.id %}"><h2>{{ i.record.title }}</h2></a>
                        <a href='/listings/search/?artist={{ i.record.artist.name }}'><h4>
                            By {{ i.record.artist.name }}</h4></a>
                        {% if i.medium == 'cd' %}
                            <p>{{ i.medium|upper }}</p>
                        {% else %}
                            <p>{{ i.medium|capfirst }}</p>

                        {% endif %}
                        {% if i.buy_now %}
                            <p class="buy-now-price">Buy now: {{ i.buy_now_price }}
                        {% endif %}
                    </div>

                </div>
            {% endif %}



            <br>
        {% endfor %}
    </div>

listings/templates/listings/main.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block header %}
    {% endblock %}
    <script src="{% static 'js/show_hide.js' %}"></script>
    <script src="{% static 'js/autocomplete.js' %}" defer></script>

</head>
<body>
<nav class="navbar">

    <ul class="navbar-left">
        <li><a href="#" onclick="showHide()">search</a></li>
        {% if user.is_authenticated %}
            <li><a href={% url 'accounts:seller_profile' user.username %}>my listings</a></li>
        {% else %}
            <li><a href={% url 'accounts:login' %}>my listings</a></li>

        {% endif %}

        <li><a href={% url 'listings:add_listing' %}>add listing</a></li>
    </ul>

    <div class="centered-image">
        <a href='/listings'><header>For The Record.</header></a> </div>

    <ul class="navbar-right">
        {% if user.is_authenticated %}
            <li><a href="/accounts/logout/">logout</a></li>
        {% else %}
            <li><a href="/accounts/login/">login</a></li>
        {% endif %}
        {% if user.is_authenticated %}
            <li><a href="/accounts/profile">profile</a></li>
        {% else %}
            <li><a href="/accounts/register">signup</a></li>
        {% endif %}



    </ul>
</nav>

<div class="searchbar" id="hidden_element" style="display: none">
    <form method="get" action="{% url 'listings:search' %}"  id="recordFilterForm">
        <div class="input-container">
            <label for="title">Title:</label>
            <div class='autocomplete-container'>
                <div class="autocomplete-input">
                    <input type="text" id="title" name="title" autocomplete="off">
                    <div id="titleSuggestions" class="autocomplete-suggestions"></div>
                </div>
            </div>
        </div>

        <div class="input-container"><label for="artist">Artist:</label>
            <div class='autocomplete-container'>
                <div class="autocomplete-input">
                    <input type="text" id="artist" name="artist" autocomplete="off">
                    <div id="artistSuggestions" class="autocomplete-suggestions"></div>
                </div>
            </div>
        </div>


        <div class="input-container"><label for="country">Country:</label>
            <div class='autocomplete-container'>
                <div class="autocomplete-input">
                    <input type="text" id="country" name="country" autocomplete="off">
                    <div id="countrySuggestions" class="autocomplete-suggestions"></div>
                </div>
            </div>
        </div>

        <div class="input-container"><label for="format">Format:</label>
            <select id="format" name="format">
                <option value="">Any</option>
                <option value="vinyl">Vinyl</option>
                <option value="cd">CD</option>
                <option value="casette">Casette</option>
            </select></div>


        <div class="input-container"><label for="year">Year:</label>
            <input type="number" id="year" name="year"></div>


        <button type="submit">Search</button>
    </form>
</div>
{% block content %}
{% endblock %}
</body>
</html>